spring:
  application:
    name: springboot-nyano
  datasource:
    url: jdbc:mysql://localhost:33306/shopdevgo
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: xxxx
    password: xxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
#            enable: true
            trust: sandbox.smtp.mailtrap.io