spring:
  application:
    name: springboot-nyano
  datasource:
    url: jdbc:mysql://localhost:33306/shopdevgo
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 97fc9f7d09e7b6
    password: 0390082ad0ad90
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
#            enable: true
            trust: sandbox.smtp.mailtrap.io
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: otp-group-id
      # consumer sẽ đọc từ offset đầu tiên (cũ nhất) trong partition. Đảm bảo comsumer không bỏ qua bất kì message nào
      # ,ngay cả khi nó chưa bao giờ được tiêu thụ từ partition
      auto-offset-reset: earliest
      enable-auto-commit: true


